services:
  fastapi:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
